# Generated by Django 3.1.1 on 2020-09-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('address_location', models.CharField(max_length=40)),
                ('phone_num', models.IntegerField(unique=True)),
                ('web_page', models.URLField(blank=True, max_length=100, null=True)),
                ('hours', models.CharField(blank=True, max_length=25, null=True)),
                ('image', models.ImageField(upload_to='img_restaurants')),
                ('date_creation', models.DateField(auto_now=True)),
                ('state_delete', models.BooleanField(default=False)),
                ('state_disponibility', models.BooleanField(default=False)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.admin')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
            },
        ),
    ]
