# Generated by Django 3.1.1 on 2020-09-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User_Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('C.C', 'Cédula de ciudadanía'), ('T.I', 'Tarjeta de identificación'), ('Passport', 'Pasaporte')], max_length=8)),
                ('document', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_num', models.IntegerField(unique=True)),
                ('email_address', models.EmailField(max_length=30, unique=True)),
                ('address_location', models.CharField(max_length=50)),
                ('state_delete', models.BooleanField(default=False)),
                ('state_disponibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Delivey_man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_vehicle', models.CharField(choices=[('bicyle', 'bicycle / monocycle'), ('motorcycle', 'motorcycle')], max_length=10)),
                ('vecicle_document', models.CharField(max_length=30)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='id_user_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_restaurant'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_staff', models.CharField(default='Admin', max_length=20)),
                ('id_user_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_restaurant')),
            ],
        ),
    ]
