# Generated by Django 3.1.1 on 2020-09-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivey_man',
            old_name='vecicle_document',
            new_name='vehicle_document',
        ),
        migrations.AddField(
            model_name='delivey_man',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img_accounts'),
        ),
    ]
