# Generated by Django 3.1.1 on 2020-09-20 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200919_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_accounts')),
                ('type_of_vehicle', models.CharField(choices=[('bicyle', 'bicycle / monocycle'), ('motorcycle', 'motorcycle')], max_length=10)),
                ('vehicle_document', models.CharField(max_length=30)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Delivey_man',
        ),
    ]
